// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The CLI (migrate/studio/etc.) needs a direct, non-pooled connection —
    // pooled connections (e.g. Supabase's Supavisor transaction pooler) don't
    // support the session-level operations migrations need. Falls back to
    // DATABASE_URL so local dev (no pooler, nothing to split) needs only one var.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
